### ISSUE TITLE
error show 

### ISSUE THREAD

**Issue by lkashyap4th** [danielgynn/express-authentication#2]
show this error why,

req.flash is not a function

**Comment by danielgynn** [comment]
@lkashyap4th Please make sure you are passing the request callback in the passport strategy config:

```
passport.use('local-login', new LocalStrategy({
    usernameField: 'email',
    passwordField: 'password',
    passReqToCallback: true,
  },
```

Also, make sure you are setting the flash in the `app.js` file:

```
app.use(flash());
```

**Comment by lkashyap4th** [comment]
hi daniel thanks for reply

but already use this code 

my code is .

api.js

var express = require('express');
var path = require('path');
var bodyParser = require('body-parser');

var port = process.env.PORT || 3000;

var passport = require('passport');
var LocalStrategy = require('passport-local').Strategy;

var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017:/tnbx_node');

var flash = require('connect-flash');
var session = require('express-session');

var app = express();

var routes = require('./routes/web');
var api = require('./routes/api');


app.use('/', routes);
app.use('/api', api);
app.use('/api/v1', api);

// view engine setup
app.set('views', './views');
app.engine('html', require('ejs').renderFile);
app.set('view engine', 'ejs');
app.use(express.static('public'));
app.use(express.static('public/storage'));

app.use(session({ 
	secret: 'lakshman' ,
	resave : false,
   	saveUninitialized : false
}));  
app.use(passport.initialize());  
app.use(passport.session());
app.use(flash());

require('./App/Config/passport')(passport);
console.log(require('./App/Config/passport'))

app.listen(port, function() {
	console.log("App Started on PORT 3000");
});

and passport.js
var LocalStrategy = require('passport-local').Strategy;
var User = require('../Models/User');

module.exports = function(passport) {  
  passport.serializeUser(function(user, done) {
    done(null, user.sno);
  });
  passport.deserializeUser(function(sno, done) {
    User.findBySno(sno, function(err, user) {
      done(err, user);
    });
  });

  // passport.use('local-signup', new LocalStrategy({
  //   usernameField: 'email',
  //   passwordField: 'password',
  //   passReqToCallback: true,
  // },
  // function(req, email, password, done) {
  //   process.nextTick(function() {
  //     User.findOne({ 'local.email':  email }, function(err, user) {
  //       if (err)
  //           return done(err);
  //       if (user) {
  //         return done(null, false, req.flash('signupMessage', 'That email is already in use.'));
  //       } else {
  //         var newUser = new User();
  //         newUser.local.email = email;
  //         newUser.local.password = newUser.generateHash(password);
  //         newUser.save(function(err) {
  //           if (err)
  //             throw err;
  //           return done(null, newUser);
  //         });
  //       }
  //     });
  //   });
  // }));

  passport.use('local', new LocalStrategy({
    usernameField: 'email',
    passwordField: 'password',
    passReqToCallback: true,
  },
  function(req, email, password, done) {
    User.findOne({ sno: 1}, function(err, user) {
      console.log(user)
      if (err)
          return done(err);
      if (!user)
          return done(null, false, { message: 'Incorrect username.' });
      // if (!user.validPassword(password))
      //     return done(null, false, { message: 'Incorrect password.' });
      return done(null, user);
    });
  }));
};

and web.js

var express = require('express');
var passport = require('passport');
var router = express.Router();
var bodyParser = require('body-parser');
router.use(bodyParser.json());
router.use(bodyParser.urlencoded({extended: true}));
// require('../App/Config/passport')(passport);

router.get('/login',function(req, res) {
	res.render('login', {
		'title':'login'
	});
});

// router.post('/signup', passport.authenticate('local-signup', {  
//   successRedirect: '/',
//   failureRedirect: '/login',
//   failureFlash: true,
// }));

router.post('/login', passport.authenticate('local', {  
  successRedirect: '/',
  failureRedirect: '/login',
  failureFlash: 'Invalid username or password',
}));

/* GET company page. */
router.get('/admin/company', isLoggedIn,function(req, res) {
	res.render('company', {
		'title':'Companies',
		'companies':[]
	});
});

router.get('/admin/company/details',isLoggedIn, function(req, res) {
	res.render('company-details', {
		'title':'Company Details',
		'companies':[]
	});
});

router.get('/admin/company/security',isLoggedIn,function(req, res) {
	res.render('security', {
		'title':'Security',
		'securities':[]
	});
});

router.get('/', function(req, res) {
	res.render('market', {
		'title':'Market',
		'market':[]
	});
});

router.get('/market/dashboard', function(req, res) {
	res.render('market-dashboard', {
		'title':'market-dashboard'
	});
});

router.get('/auction', function(req, res) {
	res.render('auction', {
		'title':'Auction',
		'auctions':[]
	});
});

router.get('/admin/company/security/auction',isLoggedIn, function(req, res) {
	res.render('auction-details', {
		'title':'Auction Details',
		'auction_details':[]
	});
});

router.get('/auction-detail',isLoggedIn, function(req, res) {
	res.render('auction-detail', {
		'title':'Auction Detail',
		'auction_detail':[]
	});
});

router.get('/admin/user', function(req, res) {
	res.render('user', {
		'title':'user',
		'user':[]
	});
});

router.get('/admin/user_details', function(req, res) {
	res.render('user-details', {
		'title':'user-details'
	});
});

router.get('/offering', function(req, res) {
	res.render('offering', {
		'title':'offering'
	});
});

module.exports = router;

function isLoggedIn(req, res, next) {  
  // if (req.isAuthenticated())
  //     return next();
  res.redirect('/login');
}
