### ISSUE TITLE
say middleware not found

### ISSUE THREAD

**Issue by lkashyap4th** [danielgynn/express-authentication#3]
passport.initialize() middleware not in use

**Comment by giacomocerquone** [comment]
Strange... passport.initialize() is called in app.js [here](https://github.com/danielgynn/express-authentication/blob/master/app.js#L36)
So maybe you changed it or I don't know 'cause it works to me!

**Comment by danielgynn** [comment]
@lkashyap4th Can you update the status of this, or close the issue?

**Comment by lkashyap4th** [comment]
solve it
