### ISSUE TITLE
state mismatch issue

### ISSUE THREAD

**Issue by arvindsinghtomar** [danielgynn/express-authentication#5]
Error processing callback Error: state mismatch
    at Client.authorizationCallback (.../..../express-authentication/node_modules/openid-client/lib/client.js:268:29)

**Comment by danielgynn** [comment]
@arvindsinghtomar can you give me some more information as to what is happening, please?

**Comment by danielgynn** [comment]
@arvindsinghtomar Closing, feel free to reopen if needed.
