### ISSUE TITLE
sign out close session. 

### ISSUE THREAD

**Issue by bigbambu** [danielgynn/express-authentication#7]
After I signed in, I am not able to sign-out the button redirects me to home but without closing the session. 
is anything that I am missing here or just the way the script it is, and I have to create a session ?

**Comment by danielgynn** [comment]
As referenced in this [SO answer](https://stackoverflow.com/a/19132999), `req.logout()` is sometimes unreliable. If this isn't working, you can try `req.session.destroy()` and redirect the user inside of the callback.
